<p>
	LA APROBACION DE PROYECTO QUE USTED ACABA DE REALIZAR,
	SERA TRANSMITIDA A NUESTRA AREA DE OPERACIONES  EN  UN
	TIEMPO DE 24 HORAS.    DURANTE ESTE PERIODO USTED PUEDRA
	MODIFICAR LA SOLICITUD COMUNICANDOSE CON SU CONTACTO  O
	CON NUESTRA AREA DE CALIDAD sico@omegaingenieros.com
</p>